apiVersion: kudo.k8s.io/v1alpha1
kind: Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    operator: mysql
  name: mysql
spec:
  operatorVersion:
    name: mysql-0.1.0
    namespace: default
    type: OperatorVersions
  # Add fields here
  parameters:
    PASSWORD: password
    BACKUP_FILE: backup.sql