apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  name: {{ .PlanName }}-job
spec:
  template:
    metadata:
      name: {{ .PlanName }}-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: bb
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - "mysqldump -u root -h mysql -p{{ .Params.PASSWORD }} kudo > /backups/{{ .Params.BACKUP_FILE }}"
        volumeMounts:
        - name: backup-pv
          mountPath: /backups
      volumes:
      - name: backup-pv
        persistentVolumeClaim:
          claimName: {{ .Name }}-backup-pv
