apiVersion: kudo.dev/v1alpha1
kind: TestSuite
manifestDirs:
- ./test/manifests/
kubectl:
- apply -f https://raw.githubusercontent.com/kudobuilder/kudo/v0.5.0/docs/deployment/10-crds.yaml
- kudo install --skip-instance ./repository/elastic/operator/
- kudo install --skip-instance ./repository/flink/operator/
- kudo install --skip-instance ./repository/kafka/operator/
- kudo install --skip-instance ./repository/mysql/operator/
- kudo install --skip-instance ./repository/redis/operator/
- kudo install --skip-instance ./repository/zookeeper/operator/
testDirs:
- ./repository/zookeeper/tests
startKIND: true
startKUDO: true
timeout: 300
