apiVersion: batch/v1
kind: Job
metadata:
  name: validation
spec:
  template:
    metadata:
      name: "validation"
    spec:
      restartPolicy: Never
      containers:
        - name: kubernetes-zookeeper
          imagePullPolicy: Always
          image: "zookeeper:3.4.14"
          env:
            - name: CONN
              value: {{ .Name }}-zookeeper-0.{{ .Name }}-hs:{{ .Params.CLIENT_PORT }},{{ .Name }}-zookeeper-1.{{ .Name }}-hs:{{ .Params.CLIENT_PORT }},{{ .Name }}-zookeeper-2.{{ .Name }}-hs:{{ .Params.CLIENT_PORT }}
          resources:
            requests:
              memory: "{{ .Params.MEMORY }}"
              cpu: "{{ .Params.CPUS }}"
          command:
            - bash
            - -c
            - "until bin/zkCli.sh -server $CONN ls /; do sleep 5; done"