apiVersion: batch/v1
kind: Job
metadata:
  name: validation
spec:
  template:
    metadata:
      name: "validation"
    spec:
      restartPolicy: Never
      containers:
        - name: kubernetes-zookeeper
          imagePullPolicy: Always
          image: "zookeeper:3.4.14"
          env:
            - name: CONN
              value: {{ if gt (int .Params.NODE_COUNT) 0 }}zookeeper-0.hs:{{ .Params.CLIENT_PORT }}{{- $root := . -}}{{ range $i, $v := untilStep 1 (int .Params.NODE_COUNT) 1 }},zookeeper-{{ $v }}.hs:{{ $root.Params.CLIENT_PORT }}{{ end }}{{ end }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
          command:
            - bash
            - -c
            - "until bin/zkCli.sh -server $CONN ls /; do sleep 5; done"
