apiVersion: kudo.k8s.io/v1alpha1
kind: Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    operator: redis
  name: rediscluster1
spec:
  operatorVersion:
    name: redis-0.1.0
    namespace: default
    type: OperatorVersion
  # Add fields here
  parameters:
    INSTANCES: "6"