apiVersion: v1
kind: Pod
spec:
  volumes:
  - name: cert-out
    emptyDir: {}
  initContainers:
    - name: init
      image: mesosphere/kafka:1.1.0-2.4.0
      command: [ "/bin/sh", "-c" ]
      args:
        - openssl req -x509 -newkey rsa:4096 -sha256 -nodes -keyout /tmp/tls.key -out /tmp/tls.crt -subj "/CN=KudoKafkaCA" -days 365
      volumeMounts:
        - name: cert-out
          mountPath: /tmp
