{{ if eq .Params.EXTERNAL_ADVERTISED_LISTENER "true" }}
{{- $root := . -}}
{{ range $i, $v := until (int .Params.BROKER_COUNT) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Name }}-kafka-{{ $v }}-external
  namespace: {{ $root.Namespace }}
spec:
  type: {{ $root.Params.EXTERNAL_ADVERTISED_LISTENER_TYPE }}
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: {{ $root.Name }}-kafka-{{ $v }}
  ports:
  - protocol: TCP
    {{ if eq  $root.Params.EXTERNAL_ADVERTISED_LISTENER_TYPE "LoadBalancer" }}
    port: {{ $root.Params.EXTERNAL_ADVERTISED_LISTENER_PORT }}
    targetPort: {{ $root.Params.EXTERNAL_ADVERTISED_LISTENER_PORT }}
    {{ end }}
    {{ if eq  $root.Params.EXTERNAL_ADVERTISED_LISTENER_TYPE "NodePort" }}
    port: {{ add (int $root.Params.EXTERNAL_NODE_PORT) $v }}
    targetPort: {{ add (int $root.Params.EXTERNAL_NODE_PORT) $v }}
    nodePort: {{ add (int $root.Params.EXTERNAL_NODE_PORT) $v }}
    {{ end }}
{{ end }}
{{ end }}
