apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pdb
  namespace: {{ .Namespace }}
spec:
  selector:
    matchLabels:
      app: kafka
      instance: {{ .Name }}
  minAvailable: 2