apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    app: confluent-schema-registry
spec:
  replicas: {{ .Params.NODE_COUNT }}
  selector:
    matchLabels:
      app: confluent-schema-registry
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: confluent-schema-registry
    spec:
      containers:
      - name: confluent-schema-registry
        image: confluentinc/cp-schema-registry:5.3.2
        command: ["/etc/confluent/docker/run"]
        resources:
          requests:
            memory: {{ .Params.MEMORY }}
            cpu: {{ .Params.CPUS }}
          limits:
            memory: {{ .Params.MEM_LIMIT }}
            cpu: {{ .Params.CPUS_LIMIT }}
        ports:
        - containerPort: {{ .Params.SCHEMA_REGISTRY_PORT }}
          name: sr-port
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: {{ .Params.HOST_NAME }}
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: {{ .Params.KAFKA_BOOTSTRAP_SERVERS }}
        livenessProbe:
          initialDelaySeconds: {{ .Params.LIVENESS_INITIAL_DELAY_SECONDS }}
          periodSeconds: {{ .Params.LIVENESS_PERIOD_SECONDS }}
          timeoutSeconds: {{ .Params.LIVENESS_TIMEOUT_SECONDS }}
          httpGet:
            path: /
            port: {{ .Params.SCHEMA_REGISTRY_PORT }}
