apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: actor
spec:
  replicas: 1
  template:
    metadata:
      name: flink-demo-actor
      labels:
        app: flink-demo-actor
    spec:
      containers:
        - name: actor
          image: mesosphere/flink-demo-actor:0.2
          command: ["/fraudDisplay-linux"]
          imagePullPolicy: Always
          args: ["--broker", "{{ .Name }}-kafka-kafka-0.{{ .Name }}-kafka-svc:9093"]