apiVersion: kudo.dev/v1alpha1
kind: Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    operator: kafka
  name: kafka
spec:
  operatorVersion:
    name: kafka-0.1.2
    namespace: default
    type: OperatorVersions
  parameters:
    ZOOKEEPER_URI: "{{ .Name }}-zk-zookeeper-0.{{ .Name }}-zk-hs:2181,{{ .Name }}-zk-zookeeper-1.{{ .Name }}-zk-hs:2181,{{ .Name }}-zk-zookeeper-2.{{ .Name }}-zk-hs:2181"
    ZOOKEEPER_PATH: "/flink-demo-kafka"
    BROKER_COUNT: "3"
    AUTO_CREATE_TOPICS_ENABLE: "true"