apiVersion: kudo.dev/v1beta1
kind: Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    operator: kafka
  name: kafka
spec:
  operatorVersion:
    name: kafka-0.1.3
    namespace: default
    type: OperatorVersions
  parameters:
    ZOOKEEPER_URI: "zk-zookeeper-0.zk-hs:2181,zk-zookeeper-1.zk-hs:2181,zk-zookeeper-2.zk-hs:2181"
    ZOOKEEPER_PATH: "/flink-demo-kafka"
    BROKER_COUNT: "3"
    AUTO_CREATE_TOPICS_ENABLE: "true"
    BROKER_MEM: "1024Mi"
