apiVersion: kudo.k8s.io/v1alpha1
kind: Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    operator: kafka
  name: kafka
spec:
  operatorVersion:
    name: kafka-0.1.0
    namespace: default
    type: OperatorVersions
  parameters:
    KAFKA_ZOOKEEPER_URI: "{{ .Name }}-zk-{{ .Name }}-zk-0.{{ .Name }}-zk-hs:2181,{{ .Name }}-zk-{{ .Name }}-zk-1.{{ .Name }}-zk-hs:2181,{{ .Name }}-zk-{{ .Name }}-zk-2.{{ .Name }}-zk-hs:2181"
    KAFKA_ZOOKEEPER_PATH: "/kafka"
    BROKER_COUNT: "3"
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"