apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: akka-cluster-demo
  namespace: {{ .Namespace }}
  labels:
    app: akka-cluster-demo
spec:
  replicas: {{ .Params.NODE_COUNT }}
  selector:
    matchLabels:
     app: akka-cluster-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: akka-cluster-demo
    spec:
      containers:
      - name: main
        image: kwehden/akka-cluster-demo:1.0.2
        readinessProbe:
          httpGet:
            path: "/ready"
            port: management
          periodSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: "/alive"
            port: management
          periodSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 20
        ports:
        - name: http
          containerPort: 8080
        - name: remoting
          containerPort: 2552
        - name: management
          containerPort: 8558
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
