apiVersion: kudo.k8s.io/v1alpha1
kind: FrameworkVersion
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: flink-0.2.0
  namespace: default
spec:
  framework:
    name: flink
    kind: Framework
  # Add fields here
  version: "0.2.0"
  parameters:
    - name: FLINK_TASKMANAGER_REPLICAS
      description: Number of task managers to run
      default: "2"
    - name: FLINK_JOBMANAGER_REPLICAS
      description: Number of job managers to run
      default: "1"
    - name: ZOOKEEPER_URL
      description: Connection information for Zookeeper
      default: "zk-zk-0.zk-hs:2181,zk-zk-1.zk-hs:2181,zk-zk-2.zk-hs:2181"
    - name: ZOOKEEPER_PATH
      description: Path to store Flink data in Zookeeper
      default: "/flink"
    - name: HIGH_AVAILABILITY
      description: Defines high-availability mode used for the cluster execution. To enable high-availability, set this mode to "ZOOKEEPER" or specify FQN of factory class.
      default: NONE
  templates:
    storage.yaml: |
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: snapshots
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
      ---
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ha
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
    services.yaml: |
      apiVersion: v1
      kind: Service
      metadata:
        name: jobmanager
        namespace: {{ .Namespace }}
      spec:
        ports:
        - name: rpc
          port: 6123
        - name: blob
          port: 6124
        - name: query
          port: 6125
        - name: ui
          port: 8081
        - name: ha
          port: 8082
        - name: metrics
          port: 8083
        selector:
          app: {{ .Name }}
          component: {{ .Name }}-jobmanager
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: hs
        namespace: {{ .Namespace }}
        labels:
          app: flink
          component: {{ .Name }}-jobmanager
      spec:
        ports:
        - name: rpc
          port: 6123
        - name: blob
          port: 6124
        - name: query
          port: 6125
        - name: ui
          port: 8081
        - name: ha
          port: 8082
        - name: metrics
          port: 8083
        selector:
          app: {{ .Name }}
          component: {{ .Name }}-jobmanager
        clusterIP: None
    taskmanager-deployment.yaml: |
      apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: taskmanager
      spec:
        replicas: {{ .Params.FLINK_TASKMANAGER_REPLICAS }}
        template:
          metadata:
            labels:
              app: flink
              component: {{ .Name }}-taskmanager
          spec:
            containers:
            - name: taskmanager
              image: kudobuilder/flink:1.7.2
              args:
              - taskmanager
              - "-Dhigh-availability={{ .Params.HIGH_AVAILABILITY }}"
              - "-Dhigh-availability.storageDir=file:///ha"
              - "-Dstate.savepoints.dir=file:///snapshots/"
              - "-Dstate.checkpoints.dir=file:///snapshots/"
              - "-Dhigh-availability.zookeeper.quorum={{ .Params.ZOOKEEPER_URL }}"
              - "-Dhigh-availability.zookeeper.path.root={{ .Params.ZOOKEEPER_PATH }}"
              - "-Dhigh-availability.cluster-id={{ .Name }}"
              - "-Dtaskmanager.rpc.port=6123"
              - "-Dtaskmanager.data.port=6121"
              - "-Dquery.server.port=6125"
              - "-Dblob.server.port=6124"
              - "-Dlog.file=/logs/jobmanager.log"
              ports:
              - containerPort: 6121
                name: data
              - containerPort: 6123
                name: rpc
              - containerPort: 6125
                name: query
              - containerPort: 8081
                name: ui
              env:
              - name: JOB_MANAGER_RPC_ADDRESS
                value: {{ .Name }}-jobmanager
              volumeMounts:
              - name: ha
                mountPath: /ha
              - name: snapshots
                mountPath: /snapshots
              - name: logs
                mountPath: /logs
            volumes:
            - name: ha
              persistentVolumeClaim:
                claimName: {{ .Name }}-ha
            - name: snapshots
              persistentVolumeClaim:
                claimName: {{ .Name }}-snapshots
            - name: logs
              emptyDir: {}
    jobmanager-deployment.yaml: |
      apiVersion: policy/v1beta1
      kind: PodDisruptionBudget
      metadata:
        name: {{ .Name }}-pdb
        namespace: {{ .Namespace }}
        labels:
          app: flink
          component: {{ .Name }}-jobmanager
      spec:
        selector:
          matchLabels:
            app: flink
            zookeeper: {{ .Name }}
      ---
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: jobmanager
      spec:
        selector:
          matchLabels:
            app: {{ .Name }}
            component: {{ .Name }}-jobmanager
        serviceName: {{ .Name }}-hs
        replicas: {{ .Params.FLINK_JOBMANAGER_REPLICAS }}
        updateStrategy:
          type: RollingUpdate
        podManagementPolicy: Parallel
        volumeClaimTemplates: []
        template:
          metadata:
            labels:
              app: {{ .Name }}
              component: {{ .Name }}-jobmanager
          spec:
            containers:
            - name: jobmanager
              image: kudobuilder/flink:1.7.2
              command: ["/opt/flink/bin/flink-console.sh"]
              args:
              - "standalonesession"
              - "-r"
              - "8081"
              - "--configDir"
              - "/opt/flink/conf"
              - "--executionMode"
              - "cluster"
              - "-Dhigh-availability={{ .Params.HIGH_AVAILABILITY }}"
              - "-Dhigh-availability.storageDir=file:///ha"
              - "-Dhigh-availability.zookeeper.quorum={{ .Params.ZOOKEEPER_URL }}"
              - "-Dhigh-availability.zookeeper.path.root={{ .Params.ZOOKEEPER_PATH }}"
              - "-Dhigh-availability.cluster-id={{ .Name }}"
              - "-Dquery.server.port=6125"
              - "-Dblob.server.port=6124"
              - "-Drest.address=$(HOSTNAME).{{ .Name }}-hs"
              - "-Dresourcemanager.rpc.port=2552"
              - "-Djobmanager.rpc.address=$(HOSTNAME).{{ .Name }}-hs"
              - "-Dhigh-availability.jobmanager.port=8082"
              - "-Dmetrics.internal.query-service.port=8083"
              - "-Dlog.file=/logs/jobmanager.log"
              - "-Dweb.upload.dir=/ha/data"
              ports:
              - containerPort: 6123
                name: rpc
              - containerPort: 6124
                name: blob
              - containerPort: 6125
                name: query
              - containerPort: 8081
                name: ui
              - containerPort: 8082
                name: ha
              - containerPort: 8083
                name: metrics
              env:
              - name: JOB_MANAGER_RPC_ADDRESS
                value: {{ .Name }}-jobmanager
              - name: log.file
                value: /logs/jobmanager.log
              - name: HOSTNAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              volumeMounts:
              - name: ha
                mountPath: /ha
              - name: snapshots
                mountPath: /snapshots
              - name: logs
                mountPath: /logs
            volumes:
            - name: ha
              persistentVolumeClaim:
                claimName: {{ .Name }}-ha
            - name: snapshots
              persistentVolumeClaim:
                claimName: {{ .Name }}-snapshots
            - name: logs
              emptyDir: {}
  tasks:
    common:
      resources:
        - storage.yaml
    jobmanager:
      resources:
        - jobmanager-deployment.yaml
    jobmanager-service:
      resources:
        - services.yaml
    taskmanager:
      resources:
        - taskmanager-deployment.yaml
  plans:
    deploy:
      strategy: serial
      phases:
        - name: flink
          strategy: serial
          steps:
            - name: jobmanager
              tasks:
                - common
                - jobmanager
                - jobmanager-service
                - taskmanager