apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  name: {{ .PlanName }}-job
spec:
  template:
    metadata:
      name: {{ .PlanName }}-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ .PlanName }}
        image: redis:5.0.1-alpine
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - 'echo yes | redis-cli -x -h {{ .Name }}-svc --cluster create --cluster-replicas 1 $(i=0; while [ $i -lt {{ .Params.masters | mul 2 }} ]; do printf $(nslookup {{ .Name }}-{{ .Name }}-${i}.{{ .Name }}-svc | grep "Address" | awk "{ print \$3 }")":{{ .Params.client_port }} "; i=$((i+1)); done)'
