apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: ClusterIP
  ports:
  - port: {{ .Params.client_port }}
    targetPort: {{ .Params.client_port }}
    name: client
  - port: {{ .Params.gossip_port }}
    targetPort: {{ .Params.gossip_port }}
    name: gossip
  selector:
    app: redis
    instance: {{ .Name }}
