apiVersion: kudo.k8s.io/v1alpha1
kind: PlanExecution
metadata:
  name: restart
  namespace: default
spec:
  instance:
    kind: Instance
    name: application
    namespace: default
  planName: restart