apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshots
  namespace: {{ .Namespace }}
spec:
  accessModes:
    - {{ .Params.flink_storage_accessmodes }}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha
  namespace: {{ .Namespace }}
spec:
  accessModes:
    - {{ .Params.flink_storage_accessmodes }}
  resources:
    requests:
      storage: 1Gi